name: journal_system
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  auto_route: ^3.2.0
  auto_size_text_field: ^1.0.1
  barcode: ^2.2.0
  barcode_widget: ^2.0.2
  bloc: ^8.0.2
  bookings_repository:
    path: packages/bookings_repository
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.5
  collapsible_sidebar: ^2.0.1+2
  dart_date: ^1.1.0
  desktop: ^3.0.1
  dio: ^4.0.4
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firestore_search: ^0.1.9
  firestore_ui: ^1.22.0
  fl_chart: ^0.41.0
  fluent_ui: ^3.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_login: ^3.1.0
  flutterfire_ui: ^0.3.0
  formz: ^0.4.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  http: ^0.13.4
  intl_phone_number_input: ^0.7.0+2
  just_the_tooltip: ^0.0.11+1
  material_floating_search_bar: ^0.3.6
  printing: ^5.6.6
  responsive_builder: ^0.4.1
  responsive_framework: ^0.1.5
  simple_timetable: ^1.0.3
  super_tooltip: ^1.0.1
  table_calendar: ^3.0.3
  time: ^2.1.0
  timelines: ^0.1.0
  timetable: ^1.0.0-alpha.6
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.0
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
