// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoVjXbbIX1djxlxV6x9AE4BIBcELQwZA8',
    appId: '1:355874360854:web:bdeb98264c8df514226f37',
    messagingSenderId: '355874360854',
    projectId: 'journalsystem-18059',
    authDomain: 'journalsystem-18059.firebaseapp.com',
    storageBucket: 'journalsystem-18059.appspot.com',
    measurementId: 'G-D0FQX58RL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEnuRaErYn4AdeAYTb-R-MsP8hfQUpiio',
    appId: '1:355874360854:android:8be95366c4ee9c93226f37',
    messagingSenderId: '355874360854',
    projectId: 'journalsystem-18059',
    storageBucket: 'journalsystem-18059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbIOWO_iYPp2gSi1s4dZRGCW9niSFEg5w',
    appId: '1:355874360854:ios:8afceabc145582de226f37',
    messagingSenderId: '355874360854',
    projectId: 'journalsystem-18059',
    storageBucket: 'journalsystem-18059.appspot.com',
    iosClientId: '355874360854-ui2hgt7cvltd5m40adatkoltouadb841.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbIOWO_iYPp2gSi1s4dZRGCW9niSFEg5w',
    appId: '1:355874360854:ios:8afceabc145582de226f37',
    messagingSenderId: '355874360854',
    projectId: 'journalsystem-18059',
    storageBucket: 'journalsystem-18059.appspot.com',
    iosClientId: '355874360854-ui2hgt7cvltd5m40adatkoltouadb841.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalSystem',
  );
}
